# action.yaml
name: 'Custom Github Action'
description: 'A Github Action that takes an input and returns the square of the number'
inputs:
  num:
    description: 'Enter a number'
    required: true
    default: "1"
outputs:
  doublenum:
    description: 'Double the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.doublenum.outputs.doublenum }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch double the input
      id: doublenum
      run: python src/doublenum.py
      shell: bash
